RecipeBook/RecipeBook.Web/Controllers/CategoryController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using RecipeBook.Bll.Services.Interfaces;
using RecipeBook.Common.Models;
using System.Threading.Tasks;

namespace RecipeBook.Web.Controllers
{
    [Authorize(Roles = "Admin, Editor")]
    public class CategoryController : Controller
    {
        private readonly ICategoryService categoryService;

        public CategoryController(ICategoryService categoryService)
        {
            this.categoryService = categoryService;
        }

        public async Task<IActionResult> GetAllAsync()
        {
            return View("List", await categoryService.GetAllAsync());
        }

        public async Task<IActionResult> DeleteAsync(int id)
        {
            if (!(await categoryService.DeleteAsync(id)))
            {
                ModelState.AddModelError("", "You can't delete it because this category is associated with a recipe");
            }

            return await GetAllAsync();
        }

        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> CreateAsync(Category category)
        {
            await categoryService.CreateAsync(category);
            return await GetAllAsync();
        }
    }
}

RecipeBook/RecipeBook.Web/Controllers/IngredientController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using RecipeBook.Bll.Services.Interfaces;
using RecipeBook.Common.Models;
using System.Threading.Tasks;

namespace RecipeBook.Web.Controllers
{
    [Authorize(Roles = "Admin, Editor")]
    public class IngredientController : Controller
    {
        private readonly IIngredientService ingredientService;

        public IngredientController(IIngredientService ingredientService)
        {
            this.ingredientService = ingredientService;
        }

        public async Task<IActionResult> GetAllAsync()
        {
            return View("List", await ingredientService.GetAllAsync());
        }

        public async Task<IActionResult> DeleteAsync(int id)
        {
            if (!(await ingredientService.DeleteAsync(id)))
            {
                ModelState.AddModelError("", "You can't delete it because this ingredient is linked to the recipe");
            }

            return await GetAllAsync();
        }

        public IActionResult Create()
        {
            ViewBag.IngredientTitle = "Add";
            return View("Edit");
        }

        public async Task<IActionResult> Update(int id)
        {
            ViewBag.IngredientTitle = "Edit";
            return View("Edit", await ingredientService.GetByIdAsync(id));
        }

        [HttpPost]
        public async Task<IActionResult> Update(Ingredient ingredient)
        {
            await ingredientService.UpdateAsync(ingredient.Id, ingredient);

            return await GetAllAsync();
        }

        [HttpPost]
        public async Task<IActionResult> CreateAsync(Ingredient ingredient)
        {
            await ingredientService.CreateAsync(ingredient);
            return await GetAllAsync();
        }
    }
}

RecipeBook/RecipeBook.Web/Controllers/RecipeController.cs
using AutoMapper;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using RecipeBook.Bll.Services.Interfaces;
using RecipeBook.Common.Models;
using RecipeBook.Web.Models;
using System.IO;
using System.Threading.Tasks;

namespace RecipeBook.Web.Controllers
{
    [Authorize(Roles = "Admin, Editor")]
    public class RecipeController : Controller
    {
        private readonly IRecipeService recipeService;
        private readonly IIngredientService ingredientService;
        private readonly ICategoryService categoryService;
        private readonly IMapper mapper;

        public RecipeController(IRecipeService recipeService, IIngredientService ingredientService, ICategoryService categoryService, IMapper mapper)
        {
            this.recipeService = recipeService;
            this.mapper = mapper;
            this.ingredientService = ingredientService;
            this.categoryService = categoryService;
        }

        [AllowAnonymous]
        public async Task<IActionResult> GetAllRecipesInfoAsync()
        {
            var recipes = await recipeService.GetAllAsync();
            return View("InfoAll", recipes);
        }

        [AllowAnonymous]
        public async Task<IActionResult> GetAllRecipesByCategoryIdAsync(int categoryId)
        {
            var recipes = await recipeService.GetAllByCategoryIdAsync(categoryId);
            return View("InfoAll", recipes);
        }

        public async Task<IActionResult> GetAllRecipesEditAsync()
        {
            return View("EditAll", await recipeService.GetAllAsync());
        }

        [AllowAnonymous]
        public async Task<IActionResult> GetByIdAsync(int id)
        {
            var recipe = await recipeService.GetByIdAsync(id);
            RecipeInfo recipeInfo = mapper.Map<RecipeInfo>(recipe);

            recipeInfo.Category = await categoryService.GetByIdAsync(recipe.CategoryId);
            recipeInfo.Ingredients = await ingredientService.GetAllByRecipeIdAsync(id);

            return View("RecipeInfoFull", recipeInfo);
        }

        [HttpGet]
        public async Task<IActionResult> UpdateAsync(int id)
        {
            var recipe = await recipeService.GetByIdAsync(id);
            RecipeViewModel recipeViewModel = mapper.Map<RecipeViewModel>(recipe);

            ViewBag.ActionTitle = "Edit";


            return View("Edit", recipeViewModel);
        }

        [HttpPost]
        public async Task<IActionResult> UpdateAsync(RecipeViewModel recipeViewModel)
        {
            if (ModelState.IsValid)
            {
                Recipe recipe = mapper.Map<Recipe>(recipeViewModel);

                recipe.ImageData = await CreateImageAsync(recipeViewModel.ImageDataFile);
                await recipeService.UpdateAsync(recipeViewModel.Id, recipe);

                return await GetAllRecipesEditAsync();
            }
            else
            {
                ViewBag.ActionTitle = "Edit";
                return View("Edit", recipeViewModel);
            }

        }

        public async Task<IActionResult> DeleteAsync(int id)
        {
            if (!(await recipeService.DeleteAsync(id)))
            {
                ModelState.AddModelError("", "The recipe cannot be deleted");
            }

            return await GetAllRecipesEditAsync();
        }

        [HttpPost]
        public async Task<IActionResult> CreateAsync(RecipeViewModel recipeViewModel)
        {
            if (ModelState.IsValid)
            {
                Recipe recipe = mapper.Map<Recipe>(recipeViewModel);

                recipe.ImageData = await CreateImageAsync(recipeViewModel.ImageDataFile);
                await recipeService.CreateAsync(recipe);

                return await GetAllRecipesEditAsync();
            }
            else
            {
                ViewBag.ActionTitle = "Create";
                return View("Edit", recipeViewModel);
            }
        }

        public IActionResult CreateAsync()
        {
            ViewBag.ActionTitle = "Create";
            return View("Edit");
        }

        private async Task<byte[]> CreateImageAsync(IFormFile imageData)
        {
            using (var memoryStream = new MemoryStream())
            {
                await imageData.CopyToAsync(memoryStream);
                return memoryStream.ToArray();
            }
        }
    }
}

RecipeBook/RecipeBook.Web/Controllers/SearchController.cs
using Microsoft.AspNetCore.Mvc;
using RecipeBook.Bll.Services.Interfaces;
using RecipeBook.Web.Models;
using System.Threading.Tasks;

namespace RecipeBook.Web.Controllers
{
    public class SearchController : Controller
    {
        private readonly IRecipeService recipeService;

        public SearchController(IRecipeService recipeService)
        {
            this.recipeService = recipeService;
        }

        [HttpGet]
        public IActionResult Index()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Index(SearchInfo searchInfo)
        {
            if (ModelState.IsValid)
            {
                var recipes = await recipeService.GetAllSearchAsync(searchInfo.CategoryId, searchInfo.IngredientsId, searchInfo.RecipeName);

                return View("~/Views/Recipe/InfoAll.cshtml", recipes);
            }
            else
            {
                return View(searchInfo);
            }
        }

    }
}

RecipeBook/RecipeBook.Web/Views/Shared/RecipeSummary.cshtml
@model Recipe




<section class="border border-info rounded col-12 load-more__item" style="margin-bottom: 10px; margin-top: 10px; padding: 10px;">

    <div class="row">

        <div class="col-md-3 col-sm-12">

            @if (Model.ImageData != null)
            {

<img class="recipeImage"
     src="data:image/jpeg;base64,@Convert.ToBase64String(Model.ImageData)" />}


        </div>

        <div class="col-md-9 col-sm-12">

            <div class="row pr-3">

                <div class="col-8">
                    <label class="text-primary" style="font-size: 21px; color: maroon">@Model.Name</label>
                </div>

            </div>

            <div class="row col-12 text-justify d-none d-md-block">

                <span class="recipe-directions__list--item">@Model.Description</span>

            </div>

            <div class="col-md-3 col-sm-12 offset-md-9 text-center">
                <a class="btn btn-success form-control" asp-controller="Recipe" asp-route-id="@Model.Id" asp-action="GetById">Details</a>
            </div>

        </div>

    </div>

</section>

RecipeBook/RecipeBook.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewBag.Title</title>



    <link rel="stylesheet" href="~/lib/font-awesome/css/all.min.css" />
    <link rel="stylesheet" href="~/lib/twitter-bootstrap/css/bootstrap.min.css" />


    <script type="text/javascript" src="~/lib/popper.js/umd/popper.min.js"></script>

    <script type="text/javascript" src="~/lib/jquery/dist/jquery.min.js"></script>



    <script type="text/javascript" src="~/lib/twitter-bootstrap/js/bootstrap.min.js"></script>
    <script type="text/javascript" src="~/bsMultiselect/js/BsMultiSelect.min.js"></script>

    <script type="text/javascript" src="~/js/site.js"></script>
    <link rel="stylesheet" href="~/css/site.css" />
    <link rel="stylesheet" href="~/css/ErrorStyle.css" />

    <script type="text/javascript" src="~/lib/jquery-validation/dist/jquery.validate.min.js"></script>

</head>

<body>

    <header class="head">
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-dark bg-dark fixed-top border-bottom box-shadow mb-3">
            <div class="container">

                <a class="navbar-brand" asp-controller="Recipe" asp-action="GetAllRecipesInfo">
                    Recipes
                </a>

                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">

                    @await Html.PartialAsync("_LoginPartial")

                    <ul class="navbar-nav flex-grow-1">

                        <li class="nav-item">
                            <a asp-controller="Search" asp-action="Index" class="nav-link">Search</a>
                        </li>

                        @if (User.IsInRole(Role.Editor.ToString()) || User.IsInRole(Role.Admin.ToString()))
                        {
                            <li class="dropdown">
                                
                                <a class="nav-link dropdown-toggle" href="#" role="button" id="dropdownMenuLink" data-bs-toggle="dropdown" aria-expanded="false">
                                    Editor
                                </a>

                                <ul class="dropdown-menu" aria-labelledby="dropdownMenuLink">
                                    <a class="dropdown-item" asp-controller="Recipe" asp-action="GetAllRecipesEdit">Recipes</a>
                                    <a class="dropdown-item" asp-controller="Category" asp-action="GetAll">Categories</a>
                                    <a class="dropdown-item" asp-controller="Ingredient" asp-action="GetAll">Ingredients</a>
                                </ul>
                                
                            </li>
                        }

                        @if (User.IsInRole(Role.Admin.ToString()))
                        {
                            <li class="nav-item">
                                <a asp-controller="Admin" asp-action="GetAll" class="nav-link">Users</a>
                            </li>
                        }

                    </ul>

                </div>
            </div>
        </nav>
    </header>



    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>
</body>

</html>