RecipeBook/RecipeBook.Web/Models/RecipeViewModel.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace RecipeBook.Web.Models
{
    public class RecipeViewModel
    {
        [Required]
        public string Name { get; set; }

        [Required]
        public TimeSpan CookingTime { get; set; }

        [Required]
        public int CookingTemperature { get; set; }

        [Required]
        public IFormFile ImageDataFile { get; set; }

        [Required]
        public string Description { get; set; }

        [Required]
        public string SequenceActions { get; set; }

        [Required]
        public int CategoryId { get; set; }

        [Required]
        public IEnumerable<int> IngredientsId { get; set; }

        [HiddenInput(DisplayValue = false)]
        public int Id { get; set; }

        public byte[] ImageData { get; set; }
    }
}

RecipeBook/RecipeBook.Web/Components/NavigationMenuViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using RecipeBook.Bll.Services.Interfaces;
using System.Threading.Tasks;

namespace RecipeBook.Web.Components
{
    public class NavigationMenuViewComponent : ViewComponent
    {
        private readonly ICategoryService categoryService;

        public NavigationMenuViewComponent(ICategoryService categoryService)
        {
            this.categoryService = categoryService;
        }

        public async Task<IViewComponentResult> InvokeAsync()
        {
            return View(await categoryService.GetAllAsync());
        }
    }
}

RecipeBook/RecipeBook.Web/Components/SelectCategoryViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using RecipeBook.Bll.Services.Interfaces;
using RecipeBook.Web.Models;
using System.Threading.Tasks;

namespace RecipeBook.Web.Components
{
    public class SelectCategoryViewComponent : ViewComponent
    {
        private readonly ICategoryService categoryService;

        public SelectCategoryViewComponent(ICategoryService categoryService)
        {
            this.categoryService = categoryService;
        }

        public async Task<IViewComponentResult> InvokeAsync(int selectCategoryId)
        {
            var category = new SelectCategoryModel
            {
                SelectCategoryId = selectCategoryId,
                Categories = await categoryService.GetAllAsync(),
            };

            return View(category);
        }
    }
}

RecipeBook/RecipeBook.Web/Components/SelectIngredientViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using RecipeBook.Bll.Services.Interfaces;
using RecipeBook.Web.Models;
using System.Collections.Generic;
using System.Threading.Tasks;

namespace RecipeBook.Web.Components
{
    public class SelectIngredientViewComponent : ViewComponent
    {
        private readonly IIngredientService ingredientService;

        public SelectIngredientViewComponent(IIngredientService ingredientService)
        {
            this.ingredientService = ingredientService;
        }

        public async Task<IViewComponentResult> InvokeAsync(IEnumerable<int> selectIngredientsId)
        {
            SelectIngredientModel selectIngredientModel = new SelectIngredientModel
            {
                AllIngredients = await ingredientService.GetAllAsync(),
                SelectIngredientsId = selectIngredientsId,
            };

            return View(selectIngredientModel);
        }
    }
}

RecipeBook/RecipeBook.Web/Controllers/DownloadController.cs
using AutoMapper;
using Microsoft.AspNetCore.Mvc;
using RecipeBook.Bll.Converter;
using RecipeBook.Bll.Services.Interfaces;
using RecipeBook.Common.Models;
using System.IO;
using System.Threading.Tasks;

namespace RecipeBook.Web.Controllers
{
    public class DownloadController : Controller
    {
        private readonly IPdfConverter pdfConverter;
        private readonly IRecipeService recipeService;
        private readonly IIngredientService ingredientService;
        private readonly ICategoryService categoryService;
        private readonly string StyleFilePath;
        private readonly IMapper mapper;

        public DownloadController(IPdfConverter pdfConverter, IRecipeService recipeService,
            IIngredientService ingredientService, ICategoryService categoryService, IMapper mapper)
        {
            this.pdfConverter = pdfConverter;
            this.recipeService = recipeService;
            this.ingredientService = ingredientService;
            this.categoryService = categoryService;
            this.mapper = mapper;
            StyleFilePath = Path.Combine(Directory.GetCurrentDirectory(), @"wwwroot\css\downloadStyle.css");
        }

        public async Task<IActionResult> GetFile(int id)
        {
            Recipe recipe = await recipeService.GetByIdAsync(id);
            RecipeInfo recipeInfo = mapper.Map<RecipeInfo>(recipe);

            recipeInfo.Category = await categoryService.GetByIdAsync(recipe.CategoryId);
            recipeInfo.Ingredients = await ingredientService.GetAllByRecipeIdAsync(id);

            var pdfFile = pdfConverter.GeneratePdfFromString(StyleFilePath, recipeInfo);
            return File(pdfFile, "application/octet-stream", $"{recipeInfo.Name}.pdf");
        }
    }
}

RecipeBook/RecipeBook.Web/Controllers/RecipeController.cs
using AutoMapper;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using RecipeBook.Bll.Services.Interfaces;
using RecipeBook.Common.Models;
using RecipeBook.Web.Models;
using System.IO;
using System.Threading.Tasks;

namespace RecipeBook.Web.Controllers
{
    [Authorize(Roles = "Admin, Editor")]
    public class RecipeController : Controller
    {
        private readonly IRecipeService recipeService;
        private readonly IIngredientService ingredientService;
        private readonly ICategoryService categoryService;
        private readonly IMapper mapper;

        public RecipeController(IRecipeService recipeService, IIngredientService ingredientService, ICategoryService categoryService, IMapper mapper)
        {
            this.recipeService = recipeService;
            this.mapper = mapper;
            this.ingredientService = ingredientService;
            this.categoryService = categoryService;
        }

        [AllowAnonymous]
        public async Task<IActionResult> GetAllRecipesInfoAsync()
        {
            var recipes = await recipeService.GetAllAsync();
            return View("InfoAll", recipes);
        }

        [AllowAnonymous]
        public async Task<IActionResult> GetAllRecipesByCategoryIdAsync(int categoryId)
        {
            var recipes = await recipeService.GetAllByCategoryIdAsync(categoryId);
            return View("InfoAll", recipes);
        }

        public async Task<IActionResult> GetAllRecipesEditAsync()
        {
            return View("EditAll", await recipeService.GetAllAsync());
        }

        [AllowAnonymous]
        public async Task<IActionResult> GetByIdAsync(int id)
        {
            var recipe = await recipeService.GetByIdAsync(id);
            RecipeInfo recipeInfo = mapper.Map<RecipeInfo>(recipe);

            recipeInfo.Category = await categoryService.GetByIdAsync(recipe.CategoryId);
            recipeInfo.Ingredients = await ingredientService.GetAllByRecipeIdAsync(id);

            return View("RecipeInfoFull", recipeInfo);
        }

        [HttpGet]
        public async Task<IActionResult> UpdateAsync(int id)
        {
            var recipe = await recipeService.GetByIdAsync(id);
            RecipeViewModel recipeViewModel = mapper.Map<RecipeViewModel>(recipe);

            ViewBag.ActionTitle = "Edit";


            return View("Edit", recipeViewModel);
        }

        [HttpPost]
        public async Task<IActionResult> UpdateAsync(RecipeViewModel recipeViewModel)
        {
            if (ModelState.IsValid)
            {
                Recipe recipe = mapper.Map<Recipe>(recipeViewModel);

                recipe.ImageData = await CreateImageAsync(recipeViewModel.ImageDataFile);
                await recipeService.UpdateAsync(recipeViewModel.Id, recipe);

                return await GetAllRecipesEditAsync();
            }
            else
            {
                ViewBag.ActionTitle = "Edit";
                return View("Edit", recipeViewModel);
            }

        }

        public async Task<IActionResult> DeleteAsync(int id)
        {
            if (!(await recipeService.DeleteAsync(id)))
            {
                ModelState.AddModelError("", "The recipe cannot be deleted");
            }

            return await GetAllRecipesEditAsync();
        }

        [HttpPost]
        public async Task<IActionResult> CreateAsync(RecipeViewModel recipeViewModel)
        {
            if (ModelState.IsValid)
            {
                Recipe recipe = mapper.Map<Recipe>(recipeViewModel);

                recipe.ImageData = await CreateImageAsync(recipeViewModel.ImageDataFile);
                await recipeService.CreateAsync(recipe);

                return await GetAllRecipesEditAsync();
            }
            else
            {
                ViewBag.ActionTitle = "Create";
                return View("Edit", recipeViewModel);
            }
        }

        public IActionResult CreateAsync()
        {
            ViewBag.ActionTitle = "Create";
            return View("Edit");
        }

        private async Task<byte[]> CreateImageAsync(IFormFile imageData)
        {
            using (var memoryStream = new MemoryStream())
            {
                await imageData.CopyToAsync(memoryStream);
                return memoryStream.ToArray();
            }
        }
    }
}

RecipeBook/RecipeBook.Web/Views/Recipe/Edit.cshtml
@model RecipeViewModel

<br />
<h2 class="text-primary">@ViewBag.ActionTitle recipe</h2>
<br />



<form form method="post" enctype="multipart/form-data"  asp-antiforgery="true">

    <div asp-validation-summary="ModelOnly" class="mainError"></div>

    <div class="border row">
        <div class="col-md-8 mt-3">

            <div class="form-group row mb-3">
                <div class="col-md-4">
                    <label class="text-primary font-weight-bold">Name</label>
                </div>
                <div class="col-md-8">
                    <input type="text" class="form-control" id="Name" name="Name" value="@Model?.Name">
                    <span asp-validation-for="Name" class="error"></span>
                </div>
            </div>

            <div class="form-group row mb-3">
                <div class="col-md-4">
                    <label class="text-primary font-weight-bold">Category</label>
                </div>
                <div class="col-md-8">
                    @await Component.InvokeAsync("SelectCategory", new { SelectCategoryId = Model?.CategoryId ?? 0 })
                    <span asp-validation-for="CategoryId" class="error"></span>

                </div>
            </div>

            <div class="form-group row mb-3">
                <div class="col-md-4">
                    <label class="text-primary font-weight-bold">Description</label>
                </div>
                <div class="col-md-8">
                    <textarea id="Description" class="form-control" name="Description">@Model?.Description</textarea>
                    <span asp-validation-for="Description" class="error"></span>
                </div>
            </div>

            <div class="form-group row mb-3">
                <div class="col-md-4">
                    <label class="text-primary font-weight-bold">Cooking time</label>
                </div>
                <div class="col-md-8">
                    <input type="time" class="form-control" id="CookingTime" name="CookingTime" value="@Model?.CookingTime">
                    <span asp-validation-for="CookingTime" class="error"></span>
                </div>
            </div>

            <div class="form-group row mb-3">
                <div class="col-md-4">
                    <label class="text-primary font-weight-bold">Image</label>
                </div>
                <div class="col-md-8">
                    <input type="file" class="form-control" id="ImageDataFile" accept=".jpg, .jpeg, .png" name="ImageDataFile" />
                    <span asp-validation-for="ImageDataFile" class="error"></span>
                </div>
            </div>


            <div class="form-group row mb-3">
                <div class="col-md-4">
                    <label class="text-primary font-weight-bold">Cooking temperature</label>
                </div>
                <div class="col-md-8">
                    <input type="number" class="form-control" id="CookingTemperature" name="CookingTemperature" value="@Model?.CookingTemperature">
                    <span asp-validation-for="CookingTemperature" class="error"></span>
                </div>
            </div>


            <div class="form-group row mb-3">
                <div class="col-md-4">
                    <label class="text-primary font-weight-bold">Sequence of actions</label>
                </div>
                <div class="col-md-8">
                    <textarea id="SequenceActions" class="form-control" name="SequenceActions">@Model?.SequenceActions</textarea>
                    <span asp-validation-for="SequenceActions" class="error"></span>
                </div>
            </div>

            <div class="form-group row mb-3">
                <div class="col-md-4">
                    <label class="text-primary font-weight-bold">Ingredients</label>
                </div>
                <div class="col-md-8">
                    @await Component.InvokeAsync("SelectIngredient", new { SelectIngredientsId = Model?.IngredientsId })
                    <span asp-validation-for="IngredientsId" class="error"></span>
                </div>
            </div>

            <div class="form-group row mb-3">
                <div class="col-md-4">

                </div>
                <div class="col-md-4">
                    <a asp-action="GetAllRecipesEdit" class="btn btn-success form-control">Back To List</a>
                </div>
                <div class="col-md-4">
                    <button type="submit" class="btn btn-primary form-control">@ViewBag.ActionTitle</button>
                </div>
            </div>
        </div>

        <div class="col-3 offset-1 d-none d-md-block">
            @if (Model?.ImageData == null)
            {
                <img id="blah" width="100%" style="border-radius:5px;border:1px solid #bbb9b9;" />
            }
            else
            {
                <img id="blah" src="data:image/jpeg;base64,@Convert.ToBase64String(Model.ImageData)" width="100%" style="border-radius:5px;border:1px solid #bbb9b9;" />
            }

        </div>

    </div>
</form>

<script type="text/javascript" src="~/js/recipe/script.js"></script>

RecipeBook/RecipeBook.Web/Views/Recipe/EditAll.cshtml
@model IEnumerable<Recipe>


<div class="border backgroundWhite">

    <div class="row align-items-center">
        <div class="col-6">
            <h2 class="text-primary">Recipes List</h2>
        </div>

        <div class="col-6">
            <div style="margin-left: 60%">
                <a class="btn btn-primary" asp-action="Create"> <i class="fas fa-plus"></i> &nbsp; Create New</a>
            </div>

        </div>
    </div>
    <br />

    <div asp-validation-summary="ModelOnly" class="mainError"></div>

    <div>
        @if (Model.Count() == 0)
        {
            <h3 class="text-center mt-3">No Recipes</h3>
        }
        else
        {
            <table class="table table-striped border">

                <thead class="table-secondary">

                    <tr>
                        <th>Name</th>
                        <th>Action</th>
                    </tr>

                </thead>

                <tbody>

                    @foreach (var item in Model)
                    {
                        <tr>
                            <td>@item.Name</td>

                            <td style="width: 150px">
                                <div class="btn btn-group" role="group">

                                    <a class="btn btn-primary" asp-action="Update" asp-route-id="@item.Id"><i class="fas fa-edit"></i></a>
                                    <a class="btn btn-danger" asp-action="Delete" asp-route-id="@item.Id"><i class="fas fa-trash-alt"></i></a>

                                </div>
                            </td>
                        </tr>
                    }
                </tbody>
            </table>
        }


    </div>
</div>

RecipeBook/RecipeBook.Web/Views/Recipe/InfoAll.cshtml
@model IEnumerable<Recipe>



<div class="backgroundWhite">


    <div id="categories" class="menu-filter-list list-inline text-center mb-4">
        @await Component.InvokeAsync("NavigationMenu")
    </div>



    <div class="row">

        <div class="col-12">

            <div class="row">
                <h3 class="text-success">Recipes</h3>
            </div>

            @if (Model.Count() == 0)
            {
                <h3 class="text-center mt-3">No Recipes</h3>
            }
            else
            {
                @foreach (var recipe in Model)
                {
                    @await Html.PartialAsync("RecipeSummary", recipe)
                }
            }


        </div>
    </div>
</div>

RecipeBook/RecipeBook.Web/Views/Recipe/RecipeFull.cshtml
@model RecipeViewModel

<br />
<h2 class="text-primary">@Model.Name</h2>
<br />



    <div class="border row">

       

        <div class="col-md-8 mt-3">

            <div class="form-group row mb-3">
                <div class="col-md-4">
                    <label class="text-primary font-weight-bold">Название</label>
                </div>
                <div class="col-md-8">
                    <label>@Model.Name</label>
                </div>
            </div>

            <div class="form-group row mb-3">
                <div class="col-md-4">
                    <label class="text-primary font-weight-bold">Категория</label>
                </div>
                <div class="col-md-8">
                    <label>@Model.Category.Name</label>
                </div>
            </div>

            <div class="form-group row mb-3">
                <div class="col-md-4">
                    <label class="text-primary font-weight-bold">Описание</label>
                </div>
                <div class="col-md-8">
                    <label>@Model.Description</label>
                </div>
            </div>

            <div class="form-group row mb-3">
                <div class="col-md-4">
                    <label class="text-primary font-weight-bold">Время готовки</label>
                </div>
                <div class="col-md-8">
                    <label>@Model.CookingTime</label>
                </div>
            </div>


            <div class="form-group row mb-3">
                <div class="col-md-4">
                    <label class="text-primary font-weight-bold">Температура готовки</label>
                </div>
                <div class="col-md-8">
                    <label>@Model.CookingTemperature.ToString("0\u00B0C")</label>
                </div>
            </div>


            <div class="form-group row mb-3">
                <div class="col-md-4">
                    <label class="text-primary font-weight-bold">Последовательность действий</label>
                </div>
                <div class="col-md-8">
                    <div class="border p-2">
                        <label>@Model.SequenceActions</label>
                    </div>
                </div>
            </div>

            <div class="form-group row mb-3">
                <div class="col-md-4">
                    <label class="text-primary font-weight-bold">Ингредиенты</label>
                </div>
                <div class="col-md-8">
                    <div class="border p-2">
                        @foreach (var ingredient in Model.Ingredients)
                        {
                            <p>@ingredient.Name, Вес - @ingredient.Weight.ToString("0.00") г</p>
                        }
                    </div>
                </div>
            </div>



            <div class="form-group row mb-3">
                <div class="col-md-4">

                </div>
                <div class="col-md-4">
                    <a asp-action="GetAllRecipes" class="btn btn-success form-control">Back To List</a>
                </div>
                <div class="col-md-4">
                    <a asp-action="GetFile" asp-controller="Download" asp-route-id="@Model.Id" class="btn btn-primary form-control">Скачать</a>
                </div>
            </div>
        </div>

        <div class="col-3 offset-1 d-none d-md-block">
            <img src="data:image/jpeg;base64,@Convert.ToBase64String(Model.ImageData)" width="100%" style="border-radius:5px;border:1px solid #bbb9b9;" />
        </div>

    </div>

RecipeBook/RecipeBook.Web/Views/Recipe/RecipeInfoFull.cshtml
@model RecipeInfo



<br />
<h2 class="text-primary">@Model.Name</h2>
<br />

    <div class="border row">
        <div class="col-md-8 mt-3">

            <div class="form-group row mb-3">
                <div class="col-md-4">
                    <label class="text-primary font-weight-bold">Name</label>
                </div>
                <div class="col-md-8">
                    <label>@Model.Name</label>
                </div>
            </div>

            <div class="form-group row mb-3">
                <div class="col-md-4">
                    <label class="text-primary font-weight-bold">Category</label>
                </div>
                <div class="col-md-8">
                    <label>@Model.Category.Name</label>
                </div>
            </div>

            <div class="form-group row mb-3">
                <div class="col-md-4">
                    <label class="text-primary font-weight-bold">Description</label>
                </div>
                <div class="col-md-8">
                    <label>@Model.Description</label>
                </div>
            </div>

            <div class="form-group row mb-3">
                <div class="col-md-4">
                    <label class="text-primary font-weight-bold">Cooking time</label>
                </div>
                <div class="col-md-8">
                    <label>@Model.CookingTime</label>
                </div>
            </div>


            <div class="form-group row mb-3">
                <div class="col-md-4">
                    <label class="text-primary font-weight-bold">Cooking temperature</label>
                </div>
                <div class="col-md-8">
                    <label>@Model.CookingTemperature.ToString("0\u00B0C")</label>
                </div>
            </div>


            <div class="form-group row mb-3">
                <div class="col-md-4">
                    <label class="text-primary font-weight-bold">Sequence of actions</label>
                </div>
                <div class="col-md-8">
                    <div class="border p-2">
                        <label>@Model.SequenceActions</label>
                    </div>
                </div>
            </div>

            <div class="form-group row mb-3">
                <div class="col-md-4">
                    <label class="text-primary font-weight-bold">Ingredients</label>
                </div>
                <div class="col-md-8">
                    <div class="border p-2">
                        @foreach (var ingredient in Model.Ingredients)
                        {
                            <p>@ingredient.Name, Weight - @ingredient.Weight.ToString("0.00") gr</p>
                        }
                    </div>
                </div>
            </div>



            <div class="form-group row mb-3">
                <div class="col-md-4">

                </div>
                <div class="col-md-4">
                    <a asp-action="GetAllRecipesInfo" class="btn btn-success form-control">Back To List</a>
                </div>
                <div class="col-md-4">
                    <a asp-action="GetFile" asp-controller="Download" asp-route-id="@Model.Id" class="btn btn-primary form-control">Download</a>
                </div>
            </div>
        </div>

        <div class="col-3 offset-1 d-none d-md-block">
            <img src="data:image/jpeg;base64,@Convert.ToBase64String(Model.ImageData)" width="100%" style="border-radius:5px;border:1px solid #bbb9b9;" />
        </div>

    </div>